### ISSUE TITLE
Implement Robolectric short taps

### ISSUE THREAD

**Issue by MarkHutchens** [TranslationWMcs435/TranslationWMcs435#33]
Make RobolectricTranslator, RobolectricFunctions, etc. Figure out what it needs that's different from preexisting frameworks.

**Comment by MarkHutchens** [comment]
Estimated time of arrival will need to be pushed back on this one. Hours of bashing my head against configurations.

**Comment by MarkHutchens** [comment]
Okay, after double-checking that it isn't my machine's fault (tried on VJ's machine too), here's the moratorium for Robolectric.

The gmdice source code has some attribute to it that prevents us from messing with it with anything junit. It appears that the different classes are not compiled when we run with junit, even though they are all clearly in the build path and classpath. We unhid all files and the problem persisted. Different errors would come up for different workarounds, but here's the one for Maven in Eclipse:

Class not found de.duenndns.gmdice.RobolectricTestCase
java.lang.ClassNotFoundException: de.duenndns.gmdice.RobolectricTestCase
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClass(RemoteTestRunner.java:685)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClasses(RemoteTestRunner.java:421)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

The build path, Maven settings, etc. all appear to be correct.

So, barring any miracles, I don't want to sink more time into a lost cause. Comments and other ideas welcome.

**Comment by MarkHutchens** [comment]
I'm not sure if I should move this to Sprint 5 or just drop it. We can discuss at the meeting in the morning. I haven't looked at it since the last post, for the record.

**Comment by nathanchen13** [comment]
I will take a look at this to see if I can get it work during Spring 5.

**Comment by MarkHutchens** [comment]
I consider this a stretch goal at this point, better to finish up on everything that is already implemented for Sprint 5. So I'm decreasing the priority.
